name: msbridge
description: "MS Bridge: A cross-platform app for seamless content reading with online/offline access, Firebase integration, and a user-friendly interface."
version: 7.5.0+12

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  page_transition: ^2.1.0
  provider: ^6.1.2
  flutter_svg: ^2.1.0
  google_nav_bar: ^5.0.7
  http: ^1.2.1
  shared_preferences: ^2.2.3
  line_icons: ^2.0.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.8.0
  flutter_highlight: ^0.7.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_colorpicker: ^1.1.0
  photo_view: ^0.15.0
  uuid: ^4.4.0
  flutter_staggered_grid_view: ^0.7.0
  rxdart: ^0.28.0
  path_provider: ^2.1.3
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  flutter_expandable_fab: ^2.0.0
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  local_auth: ^2.2.0
  dio: ^5.5.0+1
  percent_indicator: ^4.2.3
  flutter_cache_manager: ^3.3.2
  share_plus: ^10.0.2
  firebase_dynamic_links: ^6.0.8
  file_picker: ^6.1.1
  file_saver: ^0.2.12
  file_selector: ^1.0.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.1.0
  firebase_crashlytics: ^4.0.1
  firebase_analytics: ^11.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_widget_from_html: ^0.16.0
  pdf: ^3.11.0
  printing: ^5.14.0
  flutter_quill: ^9.4.3
  markdown_editable_textinput: ^2.1.0
  flutter_markdown: ^0.7.1
  google_generative_ai: ^0.4.0
  chewie: 1.6.0
  dynamic_color: ^1.8.1
  pinput: ^5.0.1
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  markdown_widget: ^2.3.2+8
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21