name: msbridge
description: "MS Bridge: A cross-platform app for seamless content reading with online/offline access, Firebase integration, and a user-friendly interface."
version: 5.0.0+5
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3
  page_transition: ^2.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  shared_preferences: ^2.2.0
  line_icons: ^2.0.3
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_html: ^3.0.0-beta.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_highlight: ^0.7.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_quill: ^9.2.0
  markdown_editable_textinput: ^2.1.0
  flutter_colorpicker: ^1.0.3
  photo_view: ^0.14.0
  uuid: ^4.5.1
  flutter_staggered_grid_view: ^0.7.0
  restart_app: ^1.2.1
  rxdart: ^0.28.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  modal_bottom_sheet: ^3.0.0
  permission_handler: ^11.3.1
  flutter_expandable_fab: ^2.3.0
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.6+2
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.6
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4
  flutter_cache_manager: ^3.4.1
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - .env
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
