name: msbridge
description: "A new Flutter project."
version: 2.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3
  page_transition: ^2.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  shared_preferences: ^2.2.0
  introduction_screen: ^3.1.17
  line_icons: ^2.0.3
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  flutter_html: ^3.0.0-beta.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  webview_flutter: ^4.8.0
  flutter_launcher_icons: ^0.14.3
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - .env
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
