name: msbridge
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.3
  # appwrite: ^14.0.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  flutter_svg: ^2.0.17
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  shared_preferences: ^2.2.0
  introduction_screen: ^3.1.17
  line_icons: ^2.0.3
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - .env
